### PR TITLE
Use the latest release snapshot.

### PR DESCRIPTION
**Pull request by eljobe**
- This also adds the missing checkstyle.xml file needed by the
  checkstyle plugin for the example to actually pass.

### CODE REVIEW

**Comment by mkordas** [comment]
@eljobe indeed with Gradle `2.14-rc4` (and final Gradle `2.14`) the problem goes away, but the same bug was introduced again in Gradle `3.0` (starting from `milestone-1`) :cry:

Can you please check it again?

**Comment by mkordas** [comment]
@eljobe did you have a chance to look into it?

**Comment by eljobe** [comment]
I have updated the forum post: https://discuss.gradle.org/t/gradle-2-14-rc-3-checkstyle-fails-when-running-from-tests/17855/12 Let's keep the discussion over there.

**Comment by eljobe** [comment]
Holy cow! I was doing some automated updates to my repositories and had totally forgotten that this one was connected with a pull-request.

@mkordas Way back in [October of last year](https://discuss.gradle.org/t/gradle-2-14-rc-3-checkstyle-fails-when-running-from-tests/17855/12?u=eljobe), I tried to reproduce your report and said that I didn't see the same problem in 3.0. Did this all get cleared up for you?

If so, let's close this pull request. I'm ready to delete my branch anyway.

**Pull request closed without merging**
